import type { Metadata } from "next";
import {
  SignedIn,
  SignedOut,
  SignInButton,
  SignUpButton,
  UserButton,
} from "@clerk/nextjs";
import { Hexagon } from "lucide-react";
import { Button } from "@/components/ui/button";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-screen grid grid-rows-[auto_1fr]">
      <header className="h-[48px] flex flex-row items-center px-4">
        <Hexagon className="min-w-8 min-h-8 hover:bg-muted p-1 rounded-md" />
        <div className="flex-1" />
        <SignedOut>
          <SignInButton />
          <SignUpButton>
            <Button size={"sm"} className="ml-4">
              Sign Up
            </Button>
          </SignUpButton>
        </SignedOut>
        <SignedIn>
          <Button size={"sm"} className="mr-4">
            <Link href="/app">Go to App</Link>
          </Button>
          <UserButton />
        </SignedIn>
      </header>
      <div className="h-full overflow-hidden">{children}</div>
    </div>
  );
}
