import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider"
import "./globals.css";
import { ReactQueryClientProvider } from "@/components/react-query-provider";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { dark, shadcn } from '@clerk/themes'
import { Header } from "@/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider
          appearance={{
            theme: [dark, shadcn]
          }}>
          <ReactQueryClientProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              disableTransitionOnChange
              enableSystem
            >
              <div className="h-screen grid grid-rows-[auto_1fr]">
                <Header />
                <div className="h-full overflow-hidden">{children}</div>
              </div>
            </ThemeProvider>
          </ReactQueryClientProvider>
        </ClerkProvider>
      </body>
    </html >
  );
}
